spec:
  inputs:
    workspace:
      type: string
      default: workspace
    repo_info_file:
      type: string
      default: config/trial-run.json
    homework_number:
      type: number
      default: -1
    last_homework_date:
      type: string
      default: ""

---

.no_schedule:
  except:
    - schedules

.python_setup: &python_setup
  variables:
    UV_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/uv"
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  image: makeappdev/cpp-dev:24.04
  before_script:
    - python -V
    - pipx install uv
    - uv venv
    - source .venv/bin/activate
    - uv pip install --upgrade -r requirements.txt

.cpp_build:
  extends: .no_schedule
  image: makeappdev/cpp-dev:24.04
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
    - make test
    - make coverage

pre-commit_checks:
  extends:
    - .no_schedule
    - .python_setup
  script:
    - pre-commit run --all-files --show-diff-on-failure

cpp_build_test_gcc:
  extends: .cpp_build

cpp_build_test_clang:
  extends: .cpp_build
  before_script:
    - use_clang.sh
  artifacts:
    expire_in: 1 week
    paths:
      - build/ccov/all-merged/

slides:
  extends: .no_schedule
  variables:
    DOCKER_TLS_CERTDIR: ""
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - apk add --no-cache --update docker make curl && rm -rf /var/cache/apk/*
    - mkdir -p ~/.docker/cli-plugins/
    - curl -SL https://github.com/docker/compose/releases/download/v2.39.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
    - chmod +x ~/.docker/cli-plugins/docker-compose
    - docker compose --version
  script:
    - mkdir -p build && chmod -R 0777 build
    - make slides
  artifacts:
    expire_in: 1 week
    paths:
      - slides/build

docs:
  extends: .no_schedule
  image: asciidoctor/docker-asciidoctor:latest
  script:
    - cd docs
    - make html
    - make pdf
  artifacts:
    expire_in: 1 week
    paths:
      - docs/output

python_tests:
  extends:
    - .no_schedule
    - .python_setup
  script:
    - make test
    - make coverage_reports
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expire_in: 1 week
    paths:
      - htmlcov
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  extends: .no_schedule
  image: makeappdev/cpp-dev:24.04
  needs:
    - cpp_build_test_clang
    - python_tests
    - slides
    - docs
  script:
    - mkdir -p public
    - mv docs/output/* public
    - mv slides/build/* public
    - mkdir -p public/export
    - make package
    - mv export/*.zip public/export
    - make solution_package
    - mv export/*.zip public/export
    - mkdir -p public/coverage
    - mv build/ccov/all-merged public/coverage/cpp
    - mv htmlcov/ public/coverage/python
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master

student_code_evaluation:
  extends: .python_setup
  only:
    - schedules
  script:
    - mkdir -p $[[ inputs.workspace ]]
    - echo "$[[ inputs.repo_info_file ]]"  # has to be set in the schedule definition
    - echo "$[[ inputs.homework_number ]]"  # has to be set in the schedule definition
    - echo "$[[ inputs.last_homework_date ]]"  # has to be set in the schedule definition
    # GITLAB_TOKEN is a protected & masked variable set in this project and contains a gitlab API token with "read_api" scope
    - python3 tools/gitlab_projects.py evaluate_code $[[ inputs.repo_info_file ]]
        --gitlab-token $GITLAB_TOKEN
        --homework-number $[[ inputs.homework_number ]]
        --date-last-homework $[[ inputs.last_homework_date ]]
        --workspace $[[ inputs.workspace ]]
    - cat $[[ inputs.workspace ]]/inactive_student_repos.md || true
  artifacts:
    paths:
      - $[[ inputs.workspace ]]/**/*-report.json
      - $[[ inputs.workspace ]]/**/*-report.md
      - $[[ inputs.workspace ]]/evaluation_report_comments_for_students.md
      - $[[ inputs.workspace ]]/**/*-diff.csv
      - $[[ inputs.workspace ]]/**/*-*.patch
      - $[[ inputs.workspace ]]/**/*-*.html
    expire_in: never
