default_stages: [commit]

ci:
  autoupdate_commit_msg: 'chore(deps): pre-commit.ci autoupdate'
  autoupdate_schedule: monthly
  autofix_commit_msg: 'style: pre-commit.ci fixes'

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: check-snake-case
        name: check snake case
        description: Check that all files are snake_case
        entry: file names and paths must be snake_case
        language: fail
        files: "-|[A-Z]"
        types_or:
          - c++
          - python
          - shell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: (?x)( .gitlab-ci.yml | .clang-format )
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: (?x)( tools/tests/code_evaluation/jobs/modules/ | tools/tests/helper.py )
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        exclude: ^slides/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-shfmt
          - mdformat-config
          - mdformat-toc
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: ["--quiet", "--config", ".md-link-config.json"]
        exclude: ^slides/homework
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping=2, --sequence=4, --offset=2, --implicit_start, --preserve-quotes]
        exclude: (?x)( .gitlab-ci.yml | .clang-format | .clang-tidy )
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--strict]
        exclude: (?x)( .clang-format | .clang-tidy | docs/theme/tum.yml )
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.3
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [cmakelang]
      - id: cmake-lint
        additional_dependencies: [cmakelang]
        exclude: cmake/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.276
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
          - flake8-use-pathlib
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-requirements
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--python-version, '3.10']
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus, --keep-runtime-typing]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.10.6
    hooks:
      - id: typos
