default_stages: [pre-commit]

ci:
  autoupdate_commit_msg: 'chore(deps): pre-commit.ci autoupdate'
  autoupdate_schedule: monthly
  autofix_commit_msg: 'style: pre-commit.ci fixes'

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: |
          (?x)^(
            .gitlab-ci.yml|
            .clang-format
          )
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: |
          (?x)^(
            tools/tests/code_evaluation/jobs/modules/|
            tools/tests/helper.py
          )
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/luminartech/dev-tools
    rev: 0.7.0
    hooks:
      - id: check-snake-case
      - id: check-cpp-and-cu-unit-test-naming-pattern
      - id: check-no-dashes
        exclude: ^slides/
      - id: check-number-of-lines-count
      - id: check-shellscript-set-options
      - id: check-non-existing-and-duplicate-excludes
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
        exclude: ^slides/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-shfmt
          - mdformat-config
          - mdformat-toc
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args: ["--quiet", "--config", ".md-link-config.json"]
        exclude: ^slides/homework
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        exclude: |
          (?x)^(
            .gitlab-ci.yml|
            .clang-tidy|
            .clang-format
          )
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
        exclude: |
          (?x)^(
            .clang-format|
            .clang-tidy|
            docs/theme/tum.yml
          )
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/PyCQA/docformatter
    # Use tag > v1.7.5 if available
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.4
    hooks:
      - id: clang-format
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [cmakelang]
      - id: cmake-lint
        additional_dependencies: [cmakelang]
        exclude: cmake/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
          - flake8-bugbear  # Ruff does not implement all of bugbear
          - flake8-requirements  # Not yet implemented https://github.com/astral-sh/ruff/issues/4100
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--python-version, '3.12']
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus, --keep-runtime-typing]
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.37
    hooks:
      - id: typos
