default_stages: [commit]

ci:
  autoupdate_commit_msg: 'chore(deps): pre-commit.ci autoupdate'
  autoupdate_schedule: monthly
  autofix_commit_msg: 'style: pre-commit.ci fixes'

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        exclude: (?x)( .gitlab-ci.yml | .clang-format )
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: (?x)( tools/tests/code_evaluation/jobs/modules/ | tools/tests/helper.py )
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        exclude: ^slides/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --implicit_start]
        exclude: (?x)( .gitlab-ci.yml | .clang-format | .clang-tidy )
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries, '88', --wrap-descriptions, '81']
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
      - id: clang-format
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [cmakelang]
      - id: cmake-lint
        additional_dependencies: [cmakelang]
        exclude: cmake/.*
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-use-pathlib
          - flake8-bugbear
          - flake8-comprehensions
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black, --multi-line, '3']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [--python-version, '3.10']
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus, --keep-runtime-typing]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.3
    hooks:
      - id: typos
