[tool.ruff]
# TODO test "ANN", "S", "DTZ", "EM", "ISC", "TRY"
select = [
    "B",
    "BLE",
    "C",
    "C4",
    "C90",
    "E",
    "ERA",
    "EXE",
    "F",
    "G",
    "ICN",
    "N",
    "PGH",
    "PIE",
    "PL",
    "PTH",
    "Q",
    "RET",
    "RUF",
    "SIM",
    "T10",
    "UP",
    "W",
    "YTT"
]
ignore = []

line-length = 120

# Assume Python 3.10.
target-version = "py310"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.docformatter]
in-place = true
recursive = true
wrap-summaries = 88
wrap-descriptions = 81
