[tool.ruff]

fix = true
ignore = []
line-length = 120
target-version = "py310"

# TODO enable "A", "S", "DTZ", "ISC"
select = [
    "B",
    "BLE",
    "C",
    "C4",
    "C90",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "G",
    "ICN",
    "N",
    "PGH",
    "PD",
    "PIE",
    "PL",
    "PTH",
    "Q",
    "RET",
    "RUF",
    "SIM",
    "T10",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT"
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.docformatter]
in-place = true
recursive = true
wrap-summaries = 88
wrap-descriptions = 81

[tool.pylint.MASTER]
# Add files or directories to the blacklist. They should be base names, not paths.
ignore = ["venv"]

[tool.pylint.BASIC]
# Stick to snake case, but accept setUp and tearDown from unittest
method-rgx = "(([a-z_][a-z0-9_]*)|(setUp)|(tearDown))$"

[tool.pylint."MESSAGES CONTROL"]
# Only show warnings with the listed confidence levels. Leave empty to show
# all. Valid levels: HIGH, INFERENCE, INFERENCE_FAILURE, UNDEFINED
confidence = ""

disable = [
    "missing-function-docstring",
    "import-error", # disabled since pre-commit runs pylint in a separate venv
    "unspecified-encoding",
    "fixme",
    "too-few-public-methods"
]

[tool.pylint.FORMAT]
max-line-length = 120
