[build-system]
requires = ["uv_build>=0.12.2,<0.13"]
build-backend = "uv_build"

[project]
name = "sel-tools"
version = "0.0.0"
description = ""
readme = "README.md"
authors = [
  {name = "Markus Hofbauer"}
]
requires-python = ">=3.12"
dependencies = [
  "coverage",
  "prek",
  "cmake-format",
  "gcovr",
  "gitpython",
  "pandas",
  "pyfakefs",
  "Pygments",
  "pytest",
  "pytest-cov",
  "pytest-sugar",
  "python-gitlab",
  "tqdm"
]

[tool.pytest.ini_options]
testpaths = [
  "tools/tests"
]

[tool.ruff]
fix = true
target-version = "py312"
line-length = 120
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN001", # Type annotation
  "ANN401",
  "ARG002",
  "COM", # Done via formatter
  "CPY001",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D203", # Incompatible with D211
  "D213", # Incompatible with D212
  "D401",
  "D417", # We don't want every argument to be documented
  "DTZ001", # TODO: Enable
  "E501", # Done via formatter
  "FBT001",
  "FBT002",
  "FBT003",
  "FIX002",
  "INP001",
  "PT", # We don't use pytest here
  "S602",
  "S604",
  "T" # Keep print statements
]

[tool.ty.rules]
invalid-type-form = "ignore"
invalid-argument-type = "ignore" # Causes issues with our inheritance structure

[tool.uv.build-backend]
module-root = "tools" # required to avoid the "src" layout, which is the default for uv_build
