services:
  html:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - ./:/documents
    command: make html
  pdf:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - ./:/documents
    command: make pdf
