name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  cpp:
    runs-on: ubuntu-latest
    container: makeappdev/cpp-dev:24.04
    strategy:
      matrix:
        include:
          - compiler: gcc
          - compiler: clang
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.compiler }}
        run: |
          use_${{ matrix.compiler }}.sh
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j8
          make test
          make coverage
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          path: build/ccov/all-merged
          name: artifacts-cpp-${{ matrix.compiler }}

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        env:
          UV_SYSTEM_PYTHON: 1
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install -r requirements.txt
      - name: Tests
        run: make test
      - name: Coverage
        run: make coverage_reports
      - uses: actions/upload-artifact@v4
        with:
          path: tools/htmlcov
          name: artifacts-python

  AsciiDoc:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Install rsync
        run: apk add rsync
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd docs
          make html
          make pdf
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          path: docs/output
          name: artifacts-docs

  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build && chmod -R 0777 build
          make slides
      - uses: actions/upload-artifact@v4
        with:
          path: slides/build
          name: artifacts-slides

  deploy:
    needs:
      - cpp
      - python
      - AsciiDoc
      - slides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Prepare Deploy
        run: |
          mkdir -p public
          mv artifacts-slides/* public
          mv artifacts-docs/* public
          mkdir -p public/coverage
          mv artifacts-cpp-clang public/coverage/cpp
          mv artifacts-python/ public/coverage/python
          mkdir -p public/export
          make package
          mv export/*.zip public/export
          make solution_package
          mv export/*.zip public/export
          echo "# This branch is for deployment only" >> public/README.md
      - name: Deploy Artifacts
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: public
          single-commit: true
          silent: true
