name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  cpp:
    runs-on: ubuntu-latest
    container: makeappdev/cpp-dev
    strategy:
      matrix:
        include:
          - compiler: gcc
          - compiler: clang
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.compiler }}
        run: |
          use_${{ matrix.compiler }}.sh
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j8
          make test
          make coverage
      - uses: actions/cache@v2
        if: ${{ matrix.compiler }} == gcc
        with:
          path: build/ccov/all-merged
          key: ${{ github.sha }}

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: make test
      - name: Coverage
        run: make coverage_reports
      - uses: actions/cache@v2
        with:
          path: tools/htmlcov
          key: ${{ github.sha }}

  AsciiDoc:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Install rsync
        run: apk add rsync
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd docs
          make html
          make pdf
      - uses: actions/cache@v2
        with:
          path: docs/output
          key: ${{ github.sha }}

  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build && chmod -R 0777 build
          make slides
      - uses: actions/cache@v2
        with:
          path: slides/build
          key: ${{ github.sha }}

  deploy:
    needs:
      - cpp
      - python
      - AsciiDoc
      - slides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            build/ccov/all-merged
            tools/htmlcov
            docs/output
            slides/build
          key: ${{ github.sha }}
      - name: Prepare Deploy
        run: |
          mkdir -p public
          mv docs/output/* public
          mv slides/build/* public
          mkdir -p public/export
          make package
          mv export/*.zip public/export
          make solution_package
          mv export/*.zip public/export
          mkdir -p public/coverage
          mv build/ccov/all-merged public/coverage/cpp
          mv tools/htmlcov/ public/coverage/python
          echo "# This branch is for deployment only" >> public/README.md
      - name: Deploy Artifacts
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: public
          single-commit: true
          silent: true
